project:
  type: website
  output-dir: docs

website:
  title: "Zak Hynd | Geospatial Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true