project:
  type: website
  output-dir: docs
  resources:
    - assets/favicon/
    - projects/assets/
    - projects/assets/leapfrog-postgresql/

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true
    include-in-header:
      - assets/_favicon.html
    include-after-body:
      - assets/_footer.html

website:
  title: "zh:"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/zak-hynd
        aria-label: GitHub
  page-footer:
    left: "© 2026 Zak Hynd"
    right:
    - icon: github
      href: https://github.com/zak-hynd
      aria-label: GitHub
    - icon: envelope
      href: "javascript:void(0)"
      aria-label: Copy email address