project:
  type: website
  output-dir: docs
  resources:
    - assets/favicon/
    - projects/assets/

website:
  title: "zh:"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true
    include-in-header:
      - assets/_favicon.html